# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 643a61a7334e93069a7a2d49ec845cc713d7409574281dc7dcfea3e584bb5bf72349fee1c5940b2efe541c2460be400539f8a363763082c49dd0225671e2fa68

test:
  secret_key_base: 1ee234a8f26b8007ec4f73bc3909736407be1a2bdead7a7aafe427ef48d555fcaa28e0d9696e57e143e225131acf6da589d57b6a98638278f696e85265b413d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
